# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeSuccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(762, 138)
        self.openExplorer = QtWidgets.QPushButton(Dialog)
        self.openExplorer.setGeometry(QtCore.QRect(170, 90, 93, 28))
        self.openExplorer.setObjectName("openExplorer")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 90, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.fileOutPath = QtWidgets.QLabel(Dialog)
        self.fileOutPath.setGeometry(QtCore.QRect(80, 30, 661, 31))
        self.fileOutPath.setStyleSheet("border-width: 1px;border-style: solid;border-color: rgb(0, 0, 0);")
        self.fileOutPath.setText("")
        self.fileOutPath.setObjectName("fileOutPath")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.openExplorer.setText(_translate("Dialog", "打开文件夹"))
        self.pushButton_2.setText(_translate("Dialog", "关闭"))
        self.label_2.setText(_translate("Dialog", "保存:"))
