# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loading(object):
    def setupUi(self, loading):
        loading.setObjectName("loading")
        loading.resize(540, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loading.sizePolicy().hasHeightForWidth())
        loading.setSizePolicy(sizePolicy)
        loading.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.load = QtWidgets.QLabel(loading)
        self.load.setGeometry(QtCore.QRect(140, 0, 252, 193))
        self.load.setToolTip("")
        self.load.setText("")
        self.load.setTextFormat(QtCore.Qt.AutoText)
        self.load.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.load.setWordWrap(True)
        self.load.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.load.setObjectName("load")

        self.retranslateUi(loading)
        QtCore.QMetaObject.connectSlotsByName(loading)

    def retranslateUi(self, loading):
        _translate = QtCore.QCoreApplication.translate
        loading.setWindowTitle(_translate("loading", "Form"))
